name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build-pages:
    name: Build MJFAX pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip3 install setuptools==58.0.0
      - run: pip3 install -r requirements.txt
      - run: python3 build_pages.py
        name: Build MJFAX pages
